// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjtaDU_xKOjKeNEy969tNz9DqUCBACN4o',
    appId: '1:518250273918:web:ff2dfc3a6e247391570c2f',
    messagingSenderId: '518250273918',
    projectId: 'alzpal-patient',
    authDomain: 'alzpal-patient.firebaseapp.com',
    storageBucket: 'alzpal-patient.appspot.com',
    measurementId: 'G-FTXK205N7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0bk_ZCR-Az--RYYBIjEO3fGsaT_G5f20',
    appId: '1:518250273918:android:d59378d7fac34bb5570c2f',
    messagingSenderId: '518250273918',
    projectId: 'alzpal-patient',
    storageBucket: 'alzpal-patient.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ3cjmURWeZckIWHNnskPYLtuQ_M56ed8',
    appId: '1:518250273918:ios:15a47a354b976104570c2f',
    messagingSenderId: '518250273918',
    projectId: 'alzpal-patient',
    storageBucket: 'alzpal-patient.appspot.com',
    iosBundleId: 'com.example.alzpalPatient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ3cjmURWeZckIWHNnskPYLtuQ_M56ed8',
    appId: '1:518250273918:ios:15a47a354b976104570c2f',
    messagingSenderId: '518250273918',
    projectId: 'alzpal-patient',
    storageBucket: 'alzpal-patient.appspot.com',
    iosBundleId: 'com.example.alzpalPatient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjtaDU_xKOjKeNEy969tNz9DqUCBACN4o',
    appId: '1:518250273918:web:23263adccf624fe7570c2f',
    messagingSenderId: '518250273918',
    projectId: 'alzpal-patient',
    authDomain: 'alzpal-patient.firebaseapp.com',
    storageBucket: 'alzpal-patient.appspot.com',
    measurementId: 'G-YD60VEJTWM',
  );
}
